#!/bin/bash

# Поднятие привилегий до root и проверка, что команда выполнена успешно
if [ "$EUID" -ne 0 ]; then
  echo "Пожалуйста, запустите скрипт с правами суперпользователя."
  exit 1
fi

cd /tmp/

# Создание репозитория для AnyDesk
cat > AnyDesk-OpenSUSE.repo << "EOF"
[anydesk]
name=AnyDesk OpenSUSE - stable
baseurl=http://rpm.anydesk.com/opensuse/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://keys.anydesk.com/repos/RPM-GPG-KEY
EOF

# Добавление репозитория и установка AnyDesk
zypper addrepo AnyDesk-OpenSUSE.repo
zypper refresh  # Обновление списка пакетов
zypper install -y anydesk  # Флаг -y для автоматического подтверждения установки

# Запуск AnyDesk
anydesk &
